/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class recognize_face */

#ifndef _Included_recognize_face
#define _Included_recognize_face
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     recognize_face
 * Method:    alloc_nn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_recognize_1face_alloc_1nn
  (JNIEnv *, jobject);

/*
 * Class:     recognize_face
 * Method:    run_data
 * Signature: (J[B)J
 */
JNIEXPORT jlong JNICALL Java_recognize_1face_run_1data
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
